[package]
name = "nomic"
version = "2.0.0"
authors = [ "The Nomic Team <hello@nomic.io>" ]
edition = "2018"
default-run = "nomic"

[dependencies]
bitcoin = "0.27.1"
bitcoind = { version = "0.21.0", features = ["22_0"], optional = true }
bitcoincore-rpc = { version = "0.14.0", optional = true }
orga = { git = "https://github.com/nomic-io/orga.git", branch="migration", features = ["merk-verify"] }
thiserror = "1.0.30"
ed = "0.3.0"
clap = { version = "3.0.0-rc.4", features = ["derive"], optional = true }
tokio = { version = "1.14.0", features = ["full"], optional = true }
base64 = "0.13.0"
js-sys = { version = "0.3.55" }
serde = "1.0.133"
serde_json = "1.0.74"
csv = { version = "1.1.6", optional = true }
bech32 = { version = "0.8.1", optional = true }
secp256k1 = "0.21.2"
futures = "0.3.21"
nomicv1 = { git = "https://github.com/nomic-io/nomic.git", branch="practicenet3-legacy", package = "nomic", optional = true }

[dev-dependencies]
chrono = "0.4.0"
bitcoin_hashes = "0.10.0"
serde_json = "1.0.68"
serde = "1.0.130"
mutagen = "0.1.2"

[features]
default = ["full"]
full = ["bitcoind", "bitcoincore-rpc", "clap", "tokio", "orga/merk-full", "orga/abci", "csv", "bech32", "nomicv1"]

[[bin]]
name = "nomic"

[[bin]]
name = "create-checkpoint"
